# Generated by Django 4.2.4 on 2023-09-16 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kkart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='Caart',
        ),
    ]
