# Generated by Django 4.2.4 on 2023-09-16 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kkart', '0003_caart_caartitem_remove_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caart',
            name='cart_id',
        ),
        migrations.RemoveField(
            model_name='caartitem',
            name='cart',
        ),
        migrations.AddField(
            model_name='caart',
            name='caart_id',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='caartitem',
            name='caart',
            field=models.ForeignKey(default='exit', on_delete=django.db.models.deletion.CASCADE, to='kkart.caart'),
            preserve_default=False,
        ),
    ]
